### ISSUE TITLE
How to build all dependencies as static libraries ?

### ISSUE THREAD

**Issue by bin-y** [cppan/cppan#13]
Hi, is there any way to build a package as shared library with all dependencies as static library?

I have tried add following to %cd%\\cppan.yml
```
local_settings:
    build:
        library_type: shared
        use_shared_libs: false
```
Everything is static library now, but I want to build package itself as shared library.
