### ISSUE TITLE
is it possible to build dependencies of Tesseract as static libraries with cppan?

### ISSUE THREAD

**Issue by goodtogood** [cppan/cppan#19]
Hi,
  is it possible to build dependencies of libtesseract as static libraries  with cppan?
just want one  libtesseract400.dll , no extra leptonica jpg gif tiff png  etc
thx.

**Comment by egorpugin** [comment]
See this issue https://github.com/cppan/cppan/issues/13

**Comment by goodtogood** [comment]
actually I noticed that issue, I tried but failed

> local_settings:
>     use_shared_libs: false
>     generator: Visual Studio 15 2017 Win64
>     silent: false
>     copy_import_libs: true
>     #build:
>         #c_flags: /W0
>         #cxx_flags: /W0
>     builds:
>         vs2017:
>             generator: Visual Studio 15 2017
>         vs2017_64:
>             generator: Visual Studio 15 2017 Win64
> 
>     dependencies:
>         pvt.cppan.demo.danbloomberg.leptonica: 1
>         pvt.cppan.demo.unicode.icu.i18n: "*"
> 
> root_project: pvt.cppan.demo.google.tesseract

**Comment by egorpugin** [comment]
Hi, please do following steps:
```
git clone https://github.com/tesseract-ocr/tesseract
cd tesseract
```
In cppan.yml set:
```
local_settings:
    use_shared_libs: false
```
```
projects:
    libtesseract:
        shared_only: true
```
Run:
```
cppan --build .
```
In `bin` dir you'll find tesseract dll with all deps statically linked.

**Comment by goodtogood** [comment]
project setting missed , thanks a lot!!

**Comment by estekitaly** [comment]
I followed the steps here, but I get a DLL in the output fulder togheter with all the EXEs, the DLL is called loc.548dfdd2.TesseractStatic.libtesseract-local.dll

this is how my cppan.yml starting part looks like:

> local_settings:
>     use_shared_libs: false
>     generator: Visual Studio 14 2015 Win64
>     silent: false
>     #copy_import_libs: true
>     build:
>         c_flags: /W0
>         cxx_flags: /W0
> 
>     dependencies:
>         pvt.cppan.demo.danbloomberg.leptonica: 1
>         pvt.cppan.demo.unicode.icu.i18n: "*"
> 
> root_project: pvt.cppan.demo.google.tesseract
> 
> common_settings:
>     c++: 11
> 
> projects:
>     libtesseract:
>         shared_only: true
>         type: lib
>         export_all_symbols: true

I just modified the `use_shared_libs: false`, `shared_only: true` and `generator: Visual Studio 14 2015 Win64`

I guess it's something about the `libtesseract` part, but I don't know which configuration/keyword I should use to make also that DLL disappear.

FYI I checked with dependency walker and ALL the EXEs have the DLL as a dependency

**Comment by clarkk** [comment]
Hi..

I'm trying to create static libs..

```
local_settings:
    use_shared_libs: true
    #generator: Visual Studio 14 2015 Win64
    silent: false
    #copy_import_libs: true
    build:
        c_flags: /W0
        cxx_flags: /W0

    dependencies:
        pvt.cppan.demo.danbloomberg.leptonica: 1
        pvt.cppan.demo.unicode.icu.i18n: "*"
...
```
and
```
projects:
    libtesseract:
        shared_only: true
        type: lib
...
```

But where do I run `cppan --build .` ?? Can't find the file `cppan` in the root dir of tesseract

Tesseract 3.05.01

**Comment by estekitaly** [comment]
@clarkk 

cppan is an external program that you have to install

**Comment by clarkk** [comment]
Sorry.. Thought I was in the Tesseract repo :)

It makes sense

But when running `cppan --build .` I get an error
```
...
-- Check size of unsigned long
-- Check size of unsigned long - failed
-- Configuring incomplete, errors occurred!
See also "/root/.cppan/storage/tmp/build/e1b2d4c1/176722e5/build/CMakeFiles/CMakeError.log".
CMake Error at /var/bin/cmake-3.9.5/Modules/TestBigEndian.cmake:49 (message):
  no suitable type found
Call Stack (most recent call first):
  .cppan/helpers.cmake:142 (test_big_endian)
  .cppan/CMakeLists.txt:98 (include)


Run command '"/usr/bin/cmake" "-H/root/.cppan/storage/tmp/build/e1b2d4c1/176722e5" "-B/root/.cppan/storage/tmp/build/e1b2d4c1/176722e5/build" "-DCMAKE_BUILD_TYPE=Release" "-DCPPAN_COMMAND=/usr/local/bin/cppan" "-DCPPAN_BUILD_VERBOSE=1" "-DCPPAN_BUILD_WARNING_LEVEL=0"', error: Operation not permitted
```

cppan installation
# cd /var/bin && wget https://cppan.org/client/cppan-master-Linux-client.deb
# dpkg -i cppan-master-Linux-client.deb

- and then made a self-upgrade

**Comment by egorpugin** [comment]
Hi @clarkk ,

Unfortunately, cppan tesseract support is not at good shape on linux.
For tesseract please use official autotools builds there.

**Comment by GilesBathgate** [comment]
@egorpugin Hi, when I build this way the --version reports local. Do you know how I can build a static Release of `tesseract.exe` Thank you.

**Comment by egorpugin** [comment]
Hi,

Try to uncomment this line:
https://github.com/tesseract-ocr/tesseract/blob/master/cppan.yml#L2
Set it to false and run `cppan --build .`

---

Or if you are using cmake, run `mkdir build && cd build && cmake .. -DSTATIC=1`.

---

There's also new way using sw (cppan v2).
Download client from https://software-network.org/
Add to PATH.
Run `sw -static build`.

**Comment by GilesBathgate** [comment]
> Try to uncomment this line:
> https://github.com/tesseract-ocr/tesseract/blob/master/cppan.yml#L2
> Set it to false and run `cppan --build .`

I have already done this, the issue is when I run `tesseract.exe --version`

```bash
tesseract local
 leptonica-1.76.0 (Mar  1 2019, 17:14:20) [MSC v.1916 LIB Release x86]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX
 Found SSE
```
In a shared build I get:
```bash
tesseract 4.0.0
 leptonica-1.76.0 (Mar  1 2019, 17:14:20) [MSC v.1916 LIB Release x86]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX
 Found SSE
```

**Comment by egorpugin** [comment]
Not sure how to get rid of that local.
So, you build static version correctly, but want to remove `local` version?

**Comment by GilesBathgate** [comment]
> So, you build static version correctly, but want to remove `local` version?
That is correct.

**Comment by GilesBathgate** [comment]
Looking at the source it comes from here: 
https://github.com/tesseract-ocr/tesseract/blob/master/src/api/baseapi.cpp#L226

```c++
/**
 * Returns the version identifier as a static string. Do not delete.
 */
const char* TessBaseAPI::Version() {
  return PACKAGE_VERSION;
}
```

**Comment by egorpugin** [comment]
This definition is provided by cppan.

**Comment by GilesBathgate** [comment]
Is it possible to configure?

**Comment by egorpugin** [comment]
In cppan.yml try to write `version: 4.0.0` starting at first column.

---

But, please, use sw.
Cppan won't be in focus anymore.

**Comment by GilesBathgate** [comment]
This is the build script I am using


```bat
@echo off

xcopy /s /y ..\Tesseract_v4\tessdata ..\bin\Tesseract\tessdata
xcopy /y cppan.yml ..\Tesseract_v4

cd ..\Tesseract_v4
git checkout master -- sw.cpp
sw -static-build build
```

cppan.yml 
```yml
version: 4.0.0

local_settings:
    use_shared_libs: false
    #short_local_names: true
    #use_cache: false
    #generator: Visual Studio 14 2015 Win64
    silent: false
    #copy_import_libs: true
    #build:
        #c_flags: /W0
        #cxx_flags: /W0
    builds:
        vs2017:
            generator: Visual Studio 15 2017
        vs2017_64:
            generator: Visual Studio 15 2017 Win64

    dependencies:
        pvt.cppan.demo.danbloomberg.leptonica: 1
        pvt.cppan.demo.unicode.icu.i18n: "*"

root_project: pvt.cppan.demo.google.tesseract

common_settings:
    c++: 11

    options:
        any:
            compile_options:
                msvc:
                    private:
                        - /openmp

projects:
    libtesseract:
        type: lib
        export_all_symbols: true
        files:

------------- snipped ------------

        dependencies:
            pvt.cppan.demo.danbloomberg.leptonica: 1

    tesseract:
        files: src/api/tesseractmain.cpp
        dependencies:
            - libtesseract
```

```bash
C:\Tesseract_v4>.sw\windows_x86_64_msvc_19.16_static_Release_4c41c7\google.tesseract.tesseract-master.exe --version
tesseract master
 leptonica-1.78.0 (Mar  2 2019, 13:41:04) [MSC v.1916 LIB Release x64]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.1 : libopenjp2 2.3.0
 Found AVX
 Found SSE
```
