### ISSUE TITLE
Changing the filename of the root project

### ISSUE THREAD

**Issue by dzjin** [cppan/cppan#29]
Hello! I've used cppan in the past for Tesseract. I have a new requirement to remove Universal CRT, which I think I have done so via my settings (copied `bin` to a new Windows installation and ran successfully).

Everything is great, except that the main tesseract file is being created as "loc.{someUuid}.tesseract-local.lib", instead of the usual "pvt.cppan.libraryName.lib". The only place I can tell that changes the name is "root_project" per this line: https://github.com/cppan/cppan/blob/master/doc/cppan.yml#L276

This is my cppan.yml, where I've removed the training portions, added /MT flag, and force static libs only.

```
local_settings:
    generator: Visual Studio 14 2015
    silent: false
    copy_import_libs: true
    build:
        c_flags: /W0
        cxx_flags: /W0
        cxx_compiler_flags_release: /MT
        cxx_compiler_flags_debug: /MT

    dependencies:
        pvt.cppan.demo.danbloomberg.leptonica: 1

root_project: pvt.cppan.demo.google.tesseract

static_only: true

common_settings:
    c++: 11

projects:
    libtesseract:
        type: lib
        export_all_symbols: true
        files:
          - api/.*\.cpp
          - arch/.*\.cpp
          - ccmain/.*\.cpp
          - ccstruct/.*\.cpp
          - ccutil/.*\.cpp
          - classify/.*\.cpp
          - cutil/.*\.cpp
          - dict/.*\.cpp
          - lstm/.*\.cpp
          - opencl/.*\.cpp
          - textord/.*\.cpp
          - viewer/.*\.cpp
          - wordrec/.*\.cpp

          - api/.*\.h
          - arch/.*\.h
          - ccmain/.*\.h
          - ccstruct/.*\.h
          - ccutil/.*\.h
          - classify/.*\.h
          - cutil/.*\.h
          - dict/.*\.h
          - lstm/.*\.h
          - opencl/.*\.h
          - textord/.*\.h
          - viewer/.*\.h
          - wordrec/.*\.h

          - vs2010/port/.*

        exclude_from_build:
          - api/tesseractmain.cpp
          - viewer/svpaint.cpp

        include_directories:
          public:
          #private:
            - arch
            - classify
            - cutil
            - ccutil
            - dict
            - lstm
            - opencl
            - textord
            - vs2010/port
            - viewer
            - wordrec
          #public:
            - api
            - ccmain
            - ccstruct
            - ccutil

        check_function_exists:
          - getline

        check_symbol_exists:
          snprintf: stdio.h

        check_include_exists:
          - dlfcn.h
          - inttypes.h
          - limits.h
          - malloc.h
          - memory.h
          - stdbool.h
          - stdint.h
          - stdlib.h
          - strings.h
          - string.h
          - sys/ipc.h
          - sys/shm.h
          - sys/stat.h
          - sys/types.h
          - sys/wait.h
          - tiffio.h
          - unistd.h

        check_type_size:
          - long long int
          - off_t
          - mbstate_t
          - wchar_t
          - _Bool

        pre_sources: |
            include(InstallRequiredSystemLibraries)
            file_write_once(${BDIR}/config_auto.h "")
            set(CMAKE_INSTALL_UCRT_LIBRARIES ON)

        post_sources: |
            set(CompilerFlags
                CMAKE_CXX_FLAGS
                CMAKE_CXX_FLAGS_DEBUG
                CMAKE_CXX_FLAGS_RELEASE
                CMAKE_C_FLAGS
                CMAKE_C_FLAGS_DEBUG
                CMAKE_C_FLAGS_RELEASE
            )
            foreach(CompilerFlag ${CompilerFlags})
                string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
            endforeach()
            if (WIN32)
                set_source_files_properties(
                    ${SDIR}/arch/dotproductsse.cpp
                    PROPERTIES COMPILE_DEFINITIONS __SSE4_1__)
                if (MSVC)
                    set_source_files_properties(
                        ${SDIR}/arch/dotproductavx.cpp
                        PROPERTIES COMPILE_FLAGS "/arch:AVX")
                endif()
            else()
                remove_src_dir(vs2010/port/*)
            endif()

        options:
            any:
                definitions:
                    public:
                      - HAVE_CONFIG_H
                      - _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1
                      - USE_STD_NAMESPACE=1
                      - WINDLLNAME="tesseract"
                      - _VCRTIMP= 
                      - _ACRTIMP= 
            shared:
                definitions:
                    private:
                        - TESS_EXPORTS
                    interface:
                        - TESS_IMPORTS

        dependencies:
            pvt.cppan.demo.danbloomberg.leptonica: 1
```
And then running this to build:
`cppan --build . --config Release`

Reason for needing this: I've gone lazy and I use Cmake prefix/suffix options when compiling a node-addon that wraps around this project, and the changing UUID does not abide by the prefix/suffix I have set (which is just "pvt.cppan.demo" and ".lib")

<img width="658" alt="screen shot 2017-11-01 at 5 38 55 pm" src="https://user-images.githubusercontent.com/6373558/32299327-9793264e-bf2b-11e7-822d-bc036e58ecad.png">

I'll appreciate any hints/directions. Thanks!
