### ISSUE TITLE
why option "compiler_flags" invalid

### ISSUE THREAD

**Issue by ZhiyangLeeCN** [cppan/cppan#30]
my cppan.yml:
local_settings:
    build:
        use_shared_libs: false
        compiler_flags: -O3 -mtune=native -mavx
dependencies:
    pvt.cppan.demo.google.tesseract.libtesseract: master
    pvt.cppan.demo.danbloomberg.leptonica: 1

I want cppan to add some compiler options when compiling dependencies. I use the command "make VERBOSE = 1 >> out.txt" to get the output in the build process. but out.txt did not find such as "-O3 -mtune = native-mavx" such output

I am not very good in English, I do not know if you understand my meaning

**Comment by egorpugin** [comment]
Hi,

In your case you probably need something like this:

```
local_settings:
  build:
    use_shared_libs: false
    use_cache: false
    compiler_flags: -O3 -mtune=native -mavx
```

**Comment by ZhiyangLeeCN** [comment]
@egorpugin I deleted the relevant .cppan directory and rebuilt it. but does not seem to work. my current configuration:
```
local_settings:
    build:
        use_shared_libs: false
        use_cache: false
        compiler_flags: -O3 -mtune=native -mavx
dependencies:
    pvt.cppan.demo.google.tesseract.libtesseract: master
    pvt.cppan.demo.danbloomberg.leptonica: 1
```

Execute one of the output of the make command:

> /usr/bin/c++  -DCPPAN -DCPPAN_API_pvt_cppan_demo_danbloomberg_leptonica_1_74_4="" -DCPPAN_API_pvt_cppan_demo_google_tesseract_libtesseract_master="" -DCPPAN_BUILD -DCPPAN_CONFIG=\"b3ba53d8\" -DCPPAN_SYMBOL_EXPORT="" -DCPPAN_SYMBOL_IMPORT="" -DHAVE_CONFIG_H -DHAVE_DLFCN_H=1 -DHAVE_FMEMOPEN=1 -DHAVE_GETLINE=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIMITS_H=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_MALLOC_H=1 -DHAVE_MEMORY_H=1 -DHAVE_OFF_T=1 -DHAVE_SIZE_T=1 -DHAVE_SNPRINTF=1 -DHAVE_STDBOOL_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRINGS_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_VOID_P=1 -DHAVE_WCHAR_T=1 -DHAVE__BOOL=1 -DPACKAGE=\"pvt.cppan.demo.google.tesseract.libtesseract\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_BUILD_CONFIG=\"Debug\" -DPACKAGE_COPYRIGHT_YEAR=2017 -DPACKAGE_NAME=\"pvt.cppan.demo.google.tesseract.libtesseract\" -DPACKAGE_NAME_LAST=\"libtesseract\" -DPACKAGE_STRING=\"38cb0305\" -DPACKAGE_URL=\"\" -DPACKAGE_VERSION=\"master\" -DSIZEOF_LONG_LONG_INT=8 -DSIZEOF_OFF_T=8 -DSIZEOF_SIZE_T=8 -DSIZEOF_VOID_P=8 -DSIZEOF_WCHAR_T=4 -DSIZEOF__BOOL=1 -DSIZE_OF_LONG_LONG_INT=8 -DSIZE_OF_OFF_T=8 -DSIZE_OF_SIZE_T=8 -DSIZE_OF_VOID_P=8 -DSIZE_OF_WCHAR_T=4 -DSIZE_OF__BOOL=1 -DUSE_STD_NAMESPACE=1 -DWINDLLNAME=\"tesseract\" -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 @CMakeFiles/38cb0305.dir/includes_CXX.rsp -std=c++11 -g -fPIC   -std=c++11 -o CMakeFiles/38cb0305.dir/arch/dotproductavx.cpp.o -c /home/zhiyanglee/.cppan/storage/src/38/cb/0305/arch/dotproductavx.cpp

Compiler flags `-O3 -mtune=native -mavx` not added.
