### ISSUE TITLE
boost iostreams fails to build - missing lzma.h in lzma.cpp file

### ISSUE THREAD

**Issue by biocomp** [cppan/cppan#33]
Not sure what to do about it.
I don't need compression part of iostreams, but not sure if there's a way to disable it.

This is my cppan.yml:
```
local_settings:
    use_shared_libs: false

    dependencies:
        pvt.cppan.demo.boost.filesystem: 1.65
        pvt.cppan.demo.boost.test: 1.65
        pvt.cppan.demo.boost.iostreams: 1.65
        pvt.cppan.demo.microsoft.gsl: master

# your project settings
shared_only: true
```
