### ISSUE TITLE
CMake generation fails with -- Thread #0: error during evaluating variables: no such file or directory

### ISSUE THREAD

**Issue by biocomp** [cppan/cppan#36]
I'm not sure what to look for, could you help?

This cppan.yaml worked fine for me:
```
local_settings:
    use_shared_libs: false

    dependencies:
        pvt.cppan.demo.boost.test: 1.65
        pvt.cppan.demo.boost.range: 1.65
        pvt.cppan.demo.boost.utility: 1.65
        pvt.cppan.demo.boost.iterator: 1.65
        pvt.cppan.demo.reactive_extensions.rxcpp: 4.0.0
```

But this one fails (additional pvt.cppan.demo.boost.iostreams line):
```
local_settings:
    use_shared_libs: false

    dependencies:
        pvt.cppan.demo.boost.test: 1.65
        pvt.cppan.demo.boost.range: 1.65
        pvt.cppan.demo.boost.utility: 1.65
        pvt.cppan.demo.boost.iterator: 1.65
        pvt.cppan.demo.boost.iostreams: 1.65
        pvt.cppan.demo.reactive_extensions.rxcpp: 4.0.0
```

Cmake cout with error is (the folders for internal-parallel-vars-check exist, I checked):
```
E:\Win81Users\UserName\Source\Repos\MyProject>"c:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 Win64" -BDebug -H. -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing 47 checks using 8 thread(s)
-- This process may take up to 10-20 minutes depending on your hardware
-- Thread #0: error during evaluating variables: no such file or directory
 0# 0x0141F079 in cppan
 1# 0x014251DE in cppan
 2# 0x0174DE8F in cppan
 3# 0x0174DFDA in cppan
 4# 0x0174DF2A in cppan
 5# set_app_type in ucrtbase
 6# BaseThreadInitThunk in KERNEL32
 7# RtlGetAppContainerNamedObjectPath in ntdll
 8# RtlGetAppContainerNamedObjectPath in ntdll

CMake Error at E:/Win81Users/UserName/.cppan/storage/etc/static/functions.cmake:676 (message):
  Last execute_process() with message 'COMMAND
  E:/Win81Users/UserName/Source/Repos/MyProject/cppan.exe

                                          internal-parallel-vars-check
                                              "E:/WIN81U~1/UserName/AppData/Local/Temp/cppan/vars/yyCulDq3"
                                              "E:/Win81Users/UserName/.cppan/storage/cfg/6d40d2d1.cmake"
                                              "E:/Win81Users/UserName/Source/Repos/MyProject/.cppan/checks.yml"
                                              "Visual Studio 15 2017 Win64"
                                              ""
                                              ""
                                          ' failed with error: 1
Call Stack (most recent call first):
  .cppan/helpers.cmake:190 (check_result_variable)
  .cppan/CMakeLists.txt:106 (include)


-- Configuring incomplete, errors occurred!
See also "E:/Win81Users/UserName/Source/Repos/MyProject/Debug/CMakeFiles/CMakeOutput.log". 
```

**Comment by egorpugin** [comment]
Maybe you could try newer client? Not uploaded yet to website. It's RelWithDebInfo, so size is a bit bigger.
[cppan.zip](https://github.com/cppan/cppan/files/1497113/cppan.zip)

**Comment by biocomp** [comment]
Thanks, definitely! 
Unfortunately, it did not help. 
CMake seems to have made a bit more progress, but still got the same error:

```
E:\Win81Users\UserName\Source\Repos\MyProject>"c:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 Win64" -BDebug3 -H. -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing 49 checks using 8 thread(s)
-- This process may take up to 10-20 minutes depending on your hardware
-- Thread #0: error during evaluating variables: no such file or directory
 0# 0x013D1099 in cppan
 1# 0x013D987E in cppan
 2# 0x0187450E in cppan
 3# 0x018745D6 in cppan
 4# 0x01874700 in cppan
 5# 0x0187443E in cppan
 6# 0x01872DB1 in cppan
 7# 0x01872CCA in cppan
 8# set_app_type in ucrtbase
 9# BaseThreadInitThunk in KERNEL32
10# RtlGetAppContainerNamedObjectPath in ntdll
11# RtlGetAppContainerNamedObjectPath in ntdll

CMake Error at E:/Win81Users/UserName/.cppan/storage/etc/static/functions.cmake:676 (message):
  Last execute_process() with message 'COMMAND
  E:/Win81Users/UserName/Source/Repos/MyProject/cppan.exe

                                          internal-parallel-vars-check
                                              "E:/WIN81U~1/UserName/AppData/Local/Temp/cppan/vars/sXX25vnR"
                                              "E:/Win81Users/UserName/.cppan/storage/cfg/6d40d2d1.cmake"
                                              "E:/Win81Users/UserName/Source/Repos/MyProject/.cppan/checks.yml"
                                              "Visual Studio 15 2017 Win64"
                                              ""
                                              ""
                                          ' failed with error: 1
Call Stack (most recent call first):
  .cppan/helpers.cmake:190 (check_result_variable)
  .cppan/CMakeLists.txt:106 (include)


-- Configuring incomplete, errors occurred!
See also "E:/Win81Users/UserName/Source/Repos/MyProject/Debug3/CMakeFiles/CMakeOutput.log".
```

**Comment by egorpugin** [comment]
Did you try to remove storage?

**Comment by biocomp** [comment]
Have just deleted .cppan folder from my user folder. Did not help. 
Did you mean something else?

**Comment by egorpugin** [comment]
No, that's correct.
You example works for me.

Code related to these checks is very ugly. I also saw such errors some time ago, I fixed some of them, but it seems not all.
This time probably I can't help you fast. I'm focusing on cppan2, so it's not really worth it to dive into such tricky errors.

> You example works for me.

I hope you mean this code (you lose some formatting when pasting here):
```
local_settings:
    storage_dir: s
    use_shared_libs: false

dependencies:
    pvt.cppan.demo.boost.test: 1.65
    pvt.cppan.demo.boost.range: 1.65
    pvt.cppan.demo.boost.utility: 1.65
    pvt.cppan.demo.boost.iterator: 1.65
    pvt.cppan.demo.boost.iostreams: 1.65
    pvt.cppan.demo.reactive_extensions.rxcpp: 4.0.0
```
