### ISSUE TITLE
How to copy pdb files to output directory on Windows?

### ISSUE THREAD

**Issue by Telokis** [cppan/cppan#61]
I am currently working on an executable project using cppan (https://gitlab.com/Telokis/Rayon) and I would like to be able to debug my project using breakpoints and other stuff.

Here is my current `cppan.yml` file:

```yml
common_settings:
  c++: 14

local_settings:
  local_build: true
  build_dir: ./.cppan/build
  build:
    configuration: Debug

files:
  - Source/.*
  - Include/.*
  - Dependencies/json/Json.cpp
  - Dependencies/json/Json.h
  - Dependencies/json/Json-forwards.h

include_directories:
  private:
    - Include/
    - Dependencies/json
    - Dependencies/glm/include

dependencies:
  - pvt.cppan.demo.boost.program_options: 1.63.0
  - pvt.cppan.demo.boost.log: 1.63.0
```

I don't use the global storage so that it is easier for my IDE (Visual Studio Code) to find the files without having to put my computer-specific path.
With this setup, I noticed those files were generated:

![image](https://user-images.githubusercontent.com/6382729/47180917-f4d85580-d321-11e8-8dfb-e237e869318e.png)

I want this `.pdb` file to move and go to the `bin` directory where my executable lies. (And also be renamed `Rayon.pdb`) so that it is picked up by my debugger automatically. 
Is there a way to do that inside my `cppan.yml` file?

Bonus question: can I ask `cppan` to build debug versions of the dependencies and also put their `pdb` files inside my `bin` output directory?

Thanks in advance for the answer!
